application: retaserver
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /.*
  script: _go_app